version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: organizer
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./back/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: app
      PGPASSWORD: app
      PGDATABASE: organizer
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db-data:


