FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci --omit=dev || npm i --omit=dev

COPY back ./back
COPY src ./src
COPY public ./public

ENV PORT=4000
EXPOSE 4000

CMD ["node", "back/app.js"]


